### ISSUE TITLE
Feature: Rulers and Guides

### ISSUE THREAD

**Issue by OverloadedOrama** [OverloadedOrama/Pixelorama#17]
Something that would be interesting to have would be rulers and guides. GIMP has them, even Godot's editor has them (see gif below).

![rulers and guides](https://user-images.githubusercontent.com/35376950/69000672-17012600-08dc-11ea-9e18-1cc2657b39f2.gif)

Since Godot has them, does that mean there is an easy way to make something like this in Pixelorama? I tried searching through the Control nodes but I couldn't find anything related to that. Any ideas?

**Comment by Calinou** [comment]
> Since Godot has them, does that mean there is an easy way to make something like this in Pixelorama? I tried searching through the Control nodes but I couldn't find anything related to that. Any ideas?

Guides in the 2D editor use a custom implementation which isn't reusable, so you'll have to do it yourself.

**Comment by OverloadedOrama** [comment]
> > Since Godot has them, does that mean there is an easy way to make something like this in Pixelorama? I tried searching through the Control nodes but I couldn't find anything related to that. Any ideas?
> 
> Rulers and guides in the 2D editor use a custom implementation which isn't reusable, so you'll have to do it yourself.

Thanks for the reply. I suspected as such. I will leave the issue open in case anyone has any ideas on how this can be implemented or wants to try to make it themselves. Otherwise I'll try to experiment with it once I do some changes to the UI.

What "scares" me the most is the visual aspect of the rulers, how is it supposed to draw these lines and numbers which are accurately based on the pixels' positions, and get bigger/smaller when zooming in and out. I'm not sure if this is something a single Label can do.

**Comment by Calinou** [comment]
@OverloadedOrama I think it might be better to implement this using `draw_line()`, `draw_multiline()` and and `draw_string()`.

**Comment by OverloadedOrama** [comment]
@Calinou I almost forgot these existed. It might be better that way indeed, I'll give it a try.

**Comment by OverloadedOrama** [comment]
I managed to implement the rulers themselves in 22c57a1b368b8920066aa52bdf188e1bfa888691 - no UI yet, only the scripts. They work almost identical to Godot's rulers. UI and guides will soon follow.

**Comment by OverloadedOrama** [comment]
Guides have been implemented in 224316256ca0a33f2a20d1f0e04bc3de1ba07ab6. More guide related stuff will be added in time, but for now I'll close this issue. If you'd like to suggest changes or report bugs, feel free to open new issues.
