### ISSUE TITLE
Color picker is picking the blue color from the lineout of the selected pixel.

### ISSUE THREAD

**Issue by azagaya** [OverloadedOrama/Pixelorama#28]
Hi!
Sometimes, when picking a color, the color picker from godot picks the color of the lineout:

![imagen](https://user-images.githubusercontent.com/46932830/69830502-d5d61380-1203-11ea-9657-301cde5ff3ef.png)

IDK if this can be solved easily.

**Comment by OverloadedOrama** [comment]
Good eye! I have noticed that myself as well. I'm not sure how this can be solved, since all the logic is being handled by Godot's color picker. However, I plan to eventually create a custom color picker with a color-selector-from-screen tool which will get the color of the pixel on the mouse's position. This should be fairly easy to do.

**Comment by azagaya** [comment]
In the meantime, until you make the custom color picker, you could not draw the blue rect if `Global.can_draw` is false. I made the test, and imho is more comfortable this way, as picking blue accidentally makes you (at best) have to go and pick color again. I can make a PR for you for this, so you can test even if you are not interested in this change.

**Comment by OverloadedOrama** [comment]
That sounds very interesting actually. A PR would be appreciated!

**Comment by azagaya** [comment]
You could also use `warp_mouse()` to move mouse always to the center of a pixel, but i think its a bit more complicated, cause you'll have to handle different rates when zooming and so.

**Comment by OverloadedOrama** [comment]
That could work, but I think your PR solved the problem already, so I guess I'll close this issue as well. Thank you for the contribution! :D

**Comment by azagaya** [comment]
You are welcome! glad to help
