### ISSUE TITLE
Possible tool features / collab

### ISSUE THREAD

**Issue by Mainman002** [OverloadedOrama/Pixelorama#5]
Hello I've been making a "simple" pixel painting app in Godot 3.1.1-Stable over the past 3 days (found here->)
https://github.com/Mainman002/Goodle

I didn't search too far into how I could contact you so I just came here (sorry for opening a conversation issue Lol)

currently my version is faking more features then actually editing images directly like yours does. I just saw your redit post and was blown away by how you managed to edit pictures like that. Anyway I doubt that you'd be able to use any of my code but feel free to check it out, maybe you might get some inspiration on a few things ;) 

I'm currently looking for ways to increase the performance of my simple pixel editor with hopes of having a canvas around 32px-64px   and so far faking things with each pixel being an object just isn't gonna work XD 

if it's alright with you could I try and learn from your program and just grab the basic canvas draw / maybe import image optimizations? I'll try to stay away from your other features as I only want to optimize what I already have vs changing it completely

**Comment by OverloadedOrama** [comment]
Hello! Thanks for contacting me, I really appreciate the fact that my program can help you! The reason I put it here publicly is to let everyone see, fix, modify, improve and even redistribute the code! Which means, you are free to do whatever you want with it. The only thing I would like is some credits for the code you're gonna use, if you use any.

I hope it will help you! Have fun with it!

**Comment by Mainman002** [comment]
awesome thank you!, your name will definitely be in the credits of my program if I use any of your code :)  just quickly looking at your code was enough to make me take a step back and realize that I have a bit more to learn Lol but honestly the way you handled things are great and technically the proper way of handling a graphics program. 

I'll keep you updated on my progress if you'd like, and if I manage to come up with a feature that you can use go ahead and use it. I'm just makin mine for fun but I have hopes of makin a pixel painter that I'd like to use myself so it's gotta work good ;)

**Comment by OverloadedOrama** [comment]
Thank you, I am very glad my project could help! I will make sure to watch your program so I will be updated on your progress!
